### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by suishii** [srviest/char-cnn-pytorch#1]
When I was training, I met a problem.
` File "train.py", line 278, in <module>
    main()
  File "train.py", line 275, in main
    train(train_loader, dev_loader, model, args)
  File "train.py", line 97, in train
    model = torch.nn.DataParallel(model).cuda()
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/parallel/data_parallel.py", line 47, in __init__
    output_device = device_ids[0]
IndexError: list index out of range
`
please help me!

**Comment by srviest** [comment]
You have to disable cuda if you run the code without gpu

**Comment by suishii** [comment]
I used gpu to run this code. But I also got this error.

**Comment by srviest** [comment]
Can you try using Python 2? Thanks for reporting the bug.
