### ISSUE TITLE
Error in Pytorch 1.0.0

### ISSUE THREAD

**Issue by Crista23** [srviest/char-cnn-pytorch#8]
Hi! I am using Pytorch 1.0.0 with Python 2.7 and I get the error below when running python train.py command:

Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  x = self.log_softmax(x)
train.py:120: UserWarning: torch.nn.utils.clip_grad_norm is now deprecated in favor of torch.nn.utils.clip_grad_norm_.
  torch.nn.utils.clip_grad_norm(model.parameters(), args.max_norm)
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    main()
  File "train.py", line 279, in main
    train(train_loader, dev_loader, model, args)
  File "train.py", line 137, in train
    loss.data[0],
IndexError: invalid index of a 0-dim tensor. Use tensor.item() to convert a 0-dim tensor to a Python number

How to fix this? Thanks!

**Comment by srviest** [comment]
fixed.
